### ISSUE TITLE
Is Xcode15 available

### ISSUE THREAD

**Issue by ChenYalun** [Xav83/tutorials#5]
Thank you for your article, I got a lot out of it!

The official version of Xcode 15 is now available, is it possible to use it on Azure Pipeline?

**Comment by Xav83** [comment]
Hi @ChenYalun :slightly_smiling_face: 

First of all, thank you a lot for this issue !! This is my first issue on this repository, so I am pretty excited :smile: 
I have created the PR #6 to update the azure pipelines configuration file about Xcode version.
As you will see in it, Xcode 15 is indeed available on Azure Pipelines, but only with the `mac-13` image.

You can also find the exhaustive list of Xcodes available on this azure pipelines image on [Azure Pipelines documentation](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode). Microsoft developers keeps it up to date when they add or remove Xcode versions (and other softwares :wink:)

**Comment by ChenYalun** [comment]
Thank you very much! I have set `vmImage: 'macOS-13'` and `xcodeVersion: '15' ` in the Azure Pipeline and it worked.
